[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["solady/=lib/solady/src/"]
solc = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

optimizer = true
optimizer_runs = 200

rpc_url = "https://rpc.testnet.sova.io"

no_match_coverage = "(script/|test/|mocks/)"

[rpc_endpoints]
base-sepolia = "https://base-sepolia.drpc.org"
optimism-sepolia = "https://opt-sepolia.g.alchemy.com/v2/S-bDSmv3do6Y2lKKT2EWfD2vTINaexjY"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }
